### ISSUE TITLE
appshelve unreadable when switching from Python3 to Python2 and vice versa

### ISSUE THREAD

**Issue by jayme-github** [jayme-github/steam_idle#11]
``` pytb
2016-02-23 13:35:11,772 (steam_idle_qt.QSteamParser.QSteamParser.updateApps) [INFO] Updating apps from steam
2016-02-23 13:35:11,774 (steamweb.steamwebbrowser.QSteamWebBrowser.get) [DEBUG] GET "https://steamcommunity.com/my/badges", kwargs: "{'params': {'p': 1}}"
Traceback (most recent call last):
  File "/home/jayme/code/steam_idle/steam_idle_qt/QSteamParser.py", line 67, in updateApps
    apps = self.sbb.get_apps()
  File "/home/jayme/code/steam_idle/steam_idle/page_parser.py", line 267, in get_apps
    a = appshelve[str(appid)]
  File "/usr/lib/python2.7/shelve.py", line 122, in __getitem__
    value = Unpickler(f).load()
ValueError: unsupported pickle protocol: 3
```

**Comment by jayme-github** [comment]
From python2 to python3 is broken to

``` pytb
2016-03-03 22:50:51,712 (steamweb.steamwebbrowser.QSteamWebBrowser.get) [DEBUG] GET "https://steamcommunity.com/my/badges", kwargs: "{'params': {'p': 2}}"
Traceback (most recent call last):
  File "/home/jayme/code/movemerge/steam_idle_qt/steam_idle_qt/QSteamParser.py", line 67, in updateApps
    apps = self.sbb.get_apps()
  File "/home/jayme/.virtualenvs/test_steamidle3/lib/python3.4/site-packages/steam_idle/page_parser.py", line 262, in get_apps
    appshelve = shelve.open(self.shelve_path)
  File "/usr/lib/python3.4/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.4/shelve.py", line 223, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.4/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
2016-03-03 22:51:01,838 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] No cleanup needed
```
