### ISSUE TITLE
What about Linux support?

### ISSUE THREAD

**Issue by PowerSlime** [jayme-github/steam_idle#13]
Py2exe... That's problem... Because linux have binary files, and without WINE there is no support of EXE files, and I can't "setup" your IDLEr

**Comment by jayme-github** [comment]
You can just install from pypi via `pip install steam_idle`.

**Comment by PowerSlime** [comment]
```
powerslime@powerslime-pc:~$ sudo pip install steam_idle
[sudo] пароль для powerslime: 
The directory '/home/powerslime/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/powerslime/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting steam_idle
  Downloading steam_idle-1.0.1.tar.gz (419kB)
    100% |████████████████████████████████| 419kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mAxHz1/steam-idle/setup.py", line 36, in <module>
        scripts = ['steam_idle_cli.py'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 270, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 706, in iter_entry_points
        entries = dist.get_entry_map(group)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2577, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2311, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mAxHz1/steam-idle/
```

I got something like this... Ubuntu 16.04 amd64 4.4.13-040413-lowlatency

**Comment by jayme-github** [comment]
I can't reproduce that. Maybe there is a problem with your python setup like described here http://stackoverflow.com/questions/17985110/errors-while-installing-python-packages

**Comment by PowerSlime** [comment]
But with other packages all is ok...

```
powerslime@powerslime-pc:~$ pip3 install vk
Collecting vk
  Downloading vk-2.0.2.tar.gz
Collecting requests<3.0,>=2.8 (from vk)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.1MB/s 
Building wheels for collected packages: vk
  Running setup.py bdist_wheel for vk ... done
  Stored in directory: /home/powerslime/.cache/pip/wheels/8d/e2/0c/056e125d54b4c9b2830ca6a7e6de00b36d416775da969abb94
Successfully built vk
Installing collected packages: requests, vk
Successfully installed requests-2.9.1 vk-2.0.2
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


powerslime@powerslime-pc:~$ pip install vk
Requirement already satisfied (use --upgrade to upgrade): vk in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests<3.0,>=2.8 in /usr/local/lib/python2.7/dist-packages (from vk)


powerslime@powerslime-pc:~$ pip install steam_idle
Collecting steam_idle
  Using cached steam_idle-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-H8R2Oi/steam-idle/setup.py", line 36, in <module>
        scripts = ['steam_idle_cli.py'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 270, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 706, in iter_entry_points
        entries = dist.get_entry_map(group)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2577, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2311, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-H8R2Oi/steam-idle/
powerslime@powerslime-pc:~$ 

```

**Comment by PowerSlime** [comment]
When I use pip3, all is good, but script can't run because I don't have steamweb library...

**Comment by PowerSlime** [comment]
```
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ python steam_idle_gui.py 
Traceback (most recent call last):
  File "steam_idle_gui.py", line 13, in <module>
    from steam_idle_qt.ui.mainwindow import MainWindow
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/ui/mainwindow.py", line 14, in <module>
    from .settingsdialog import SettingsDialog
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/ui/settingsdialog.py", line 11, in <module>
    from steam_idle_qt.QSteamWebBrowser import QSteamWebBrowser
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/QSteamWebBrowser.py", line 3, in <module>
    from steamweb import SteamWebBrowser
ImportError: No module named steamweb
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ 
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ 
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ python3 steam_idle_gui.py 
Traceback (most recent call last):
  File "steam_idle_gui.py", line 12, in <module>
    from PyQt4 import QtGui
ImportError: No module named 'PyQt4'
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ 
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ 
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ ./steam_idle_gui.py 
Traceback (most recent call last):
  File "./steam_idle_gui.py", line 13, in <module>
    from steam_idle_qt.ui.mainwindow import MainWindow
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/ui/mainwindow.py", line 14, in <module>
    from .settingsdialog import SettingsDialog
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/ui/settingsdialog.py", line 11, in <module>
    from steam_idle_qt.QSteamWebBrowser import QSteamWebBrowser
  File "/home/powerslime/Загрузки/steam_idle_qt-master/steam_idle_qt/QSteamWebBrowser.py", line 3, in <module>
    from steamweb import SteamWebBrowser
ImportError: No module named steamweb
powerslime@powerslime-pc:~/Загрузки/steam_idle_qt-master$ 

```
