### ISSUE TITLE
Badge page error too many 503

### ISSUE THREAD

**Issue by ghost** [jayme-github/steam_idle#7]
This is the badge page error I mentioned on another thread.

Sorry if this is in the wrong place, I thought it was a `steam_idle` thing but it might be a `steamweb` thing. Thanks!

``` pytb
Traceback (most recent call last):
  File "/home/nick/bin/steam_idle/steam_idle_cli.py", line 153, in <module>
    main_idle(apps)
  File "/home/nick/bin/steam_idle/steam_idle_cli.py", line 85, in main_idle
    for a in sbb.get_apps(fetch_images=False).values():
  File "/home/nick/bin/steam_idle/steam_idle/page_parser.py", line 252, in get_apps
    apps = self.parse_badges_pages(appid_filter)
  File "/home/nick/bin/steam_idle/steam_idle/page_parser.py", line 170, in parse_badges_pages
    r = self.swb.get('https://steamcommunity.com/my/badges', params={'p': currentPage})
  File "/home/nick/.local/lib/python2.7/site-packages/steamweb/steamwebbrowser.py", line 195, in get
    r = self.session.get(url, **kwargs)
  File "/home/nick/.local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/nick/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nick/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/nick/.local/lib/python2.7/site-packages/requests/adapters.py", line 421, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='steamcommunity.com', port=443): Max retries exceeded with url: /my/badges?p=1 (Caused by ResponseError('too many 503 error responses',))
```

**Comment by jayme-github** [comment]
That's most likely an steamweb problem but don't mind. Are you running an up-to-date steamweb version? I made some changes in jayme-github/steamweb@56a5b432088e70ca38840b06a5b9e412d4504af8 and jayme-github/steamweb@67b78bd4cafc2afc9b79413835ff7c054130b174 that should retry requests two times in case of 503. If steam still responds with 503 there is not much we can do.

**Comment by ghost** [comment]
Yes I was running the most recent version.

**Comment by jayme-github** [comment]
I've added some code to avoid those profile redirects. Please check if the problem still persists with jayme-github/steamweb@8da4d764eaf394ac4850147f919f0b3da7895b49

**Comment by ghost** [comment]
I haven't had this issue anymore. Seems to work well.
