### ISSUE TITLE
Traceback when idle on last app is finished

### ISSUE THREAD

**Issue by jayme-github** [jayme-github/steam_idle#9]
```
2016-01-20 10:21:38,510 (steamweb.steamwebbrowser.QSteamWebBrowser.get) [DEBUG] GET "https://steamcommunity.com/my/badges", kwargs: "{'params': {'p': 1}}"
2016-01-20 10:21:38,511 (steam_idle_qt.ui.mainwindow.MainWindow.on_SteamParser_stopTimer) [DEBUG] Stopping timer and hiding labelStatusBarTimer
2016-01-20 10:21:38,512 (steam_idle_qt.ui.mainwindow.MainWindow.on_SteamParser_startTimer) [DEBUG] 60000
2016-01-20 10:21:41,379 (steam_idle_qt.QSteamParser.QSteamParser.updateApps) [DEBUG] ParseApps: 193 apps
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] on_steamDataReady with 193 apps as parameter
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] updated app: OLD: <[416080] "God Game : The Odyssey" (1, 1.0)>
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] updated app: NEW: <[416080] "God Game : The Odyssey" (0, 1.5)>
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle._idle) [INFO] No drops left, stopping idle and emitting appDone signal
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] _stopIdle called
2016-01-20 10:21:41,380 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] Terminating child
2016-01-20 10:21:41,380 (steam_idle_qt.ui.mainwindow.MainWindow.updateSteamData) [DEBUG] updateSteamData with 193 apps as parameter
2016-01-20 10:21:41,384 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] Child terminated
2016-01-20 10:21:41,394 (steam_idle_qt.ui.mainwindow.MainWindow.on_idleAppDone) [DEBUG] activeApps: "[<[416080] "God Game : The Odyssey" (3, 0.0)>]"
2016-01-20 10:21:41,394 (steam_idle_qt.ui.mainwindow.MainWindow.nextAppWithDrops) [DEBUG] (183, 183): <[363490] "Escape Machines" (0, 3.5)>
...
2016-01-20 10:21:41,403 (steam_idle_qt.ui.mainwindow.MainWindow.nextAppWithDrops) [DEBUG] (182, 182): <[416080] "God Game : The Odyssey" (0, 1.5)>
2016-01-20 10:21:41,403 (steam_idle_qt.ui.mainwindow.MainWindow.on_idleAppDone) [DEBUG] nextApp: "None"
2016-01-20 10:21:41,403 (steam_idle_qt.ui.mainwindow.MainWindow.on_idleAppDone) [DEBUG] No next app found. stop idle
2016-01-20 10:21:41,403 (steam_idle_qt.ui.mainwindow.MainWindow.updateSteamData) [DEBUG] updateSteamData with 0 apps as parameter
2016-01-20 10:21:41,403 (steam_idle_qt.QIdle.Idle.doStopIdle) [DEBUG] doStopIdle called
2016-01-20 10:21:41,404 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] _stopIdle called
2016-01-20 10:21:41,404 (steam_idle_qt.QIdle.Idle.doStopIdle) [DEBUG] sending finished signal
2016-01-20 10:21:41,404 (steam_idle_qt.QSteamParser.QSteamParser.stopTimer) [DEBUG] Stopping timer
2016-01-20 10:21:41,418 (steam_idle_qt.ui.mainwindow.MainWindow._post_stopIdle) [DEBUG] activeApps: "[<[416080] "God Game : The Odyssey" (3, 0.0)>]"
2016-01-20 10:21:41,418 (steam_idle_qt.ui.mainwindow.MainWindow.startProgressBar) [DEBUG] startProgressBar: Loading data from Steam...
2016-01-20 10:21:41,419 (steam_idle_qt.QSteamParser.QSteamParser.updateApps) [INFO] Updating apps from steam
2016-01-20 10:21:41,419 (steam_idle_qt.ui.mainwindow.MainWindow.on_SteamParser_stopTimer) [DEBUG] Stopping timer and hiding labelStatusBarTimer
2016-01-20 10:21:41,419 (steamweb.steamwebbrowser.QSteamWebBrowser.get) [DEBUG] GET "https://steamcommunity.com/my/badges", kwargs: "{'params': {'p': 1}}"
2016-01-20 10:21:43,027 (steam_idle_qt.ui.mainwindow.MainWindow.checkSteamRunning) [INFO] autostartMode: "Idle"
2016-01-20 10:21:43,028 (steam_idle_qt.ui.mainwindow.MainWindow.checkSteamRunning) [DEBUG] Autostart Idle
2016-01-20 10:21:43,028 (steam_idle_qt.ui.mainwindow.MainWindow.nextAppWithDrops) [DEBUG] (0, 0): <[243200] "Memoria" (0, 1.5)>
...
2016-01-20 10:21:43,036 (steam_idle_qt.ui.mainwindow.MainWindow.nextAppWithDrops) [DEBUG] (192, 192): <[270330] "Ku: Shroud of the Morrigan" (0, 3.2)>
2016-01-20 10:21:43,036 (steam_idle_qt.ui.mainwindow.MainWindow.startIdle) [DEBUG] activeApps: "[None]"
Traceback (most recent call last):
  File "/home/code/steam_idle/steam_idle_qt/ui/mainwindow.py", line 180, in checkSteamRunning
    self.on_actionStartStopIdle_triggered()
  File "/home/code/steam_idle/steam_idle_qt/ui/mainwindow.py", line 570, in on_actionStartStopIdle_triggered
    self.startIdle(self.nextAppWithDrops())
  File "/home/code/steam_idle/steam_idle_qt/ui/mainwindow.py", line 266, in startIdle
    Q_ARG(App, app))
TypeError: Python type 'App' is not supported as a Q_ARG() type
2016-01-20 10:21:44,313 (steam_idle_qt.QSteamParser.QSteamParser.updateApps) [DEBUG] ParseApps: 193 apps
2016-01-20 10:21:44,313 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] on_steamDataReady with 193 apps as parameter
2016-01-20 10:21:44,313 (steam_idle_qt.ui.mainwindow.MainWindow.updateSteamData) [DEBUG] updateSteamData with 193 apps as parameter
2016-01-20 10:21:44,313 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] updated app: OLD: <[416080] "God Game : The Odyssey" (0, 1.5)>
2016-01-20 10:21:44,314 (steam_idle_qt.QIdle.Idle.on_steamDataReady) [DEBUG] updated app: NEW: <[416080] "God Game : The Odyssey" (0, 1.5)>
2016-01-20 10:21:44,314 (steam_idle_qt.QIdle.Idle._idle) [INFO] No drops left, stopping idle and emitting appDone signal
2016-01-20 10:21:44,314 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] _stopIdle called
2016-01-20 10:21:44,327 (steam_idle_qt.ui.mainwindow.MainWindow.on_idleAppDone) [DEBUG] activeApps: "[None]"
Traceback (most recent call last):
  File "/home/code/steam_idle/steam_idle_qt/ui/mainwindow.py", line 616, in on_idleAppDone
    rowId = self.rowIdForAppId(self.activeApps[0].appid)
AttributeError: 'NoneType' object has no attribute 'appid'

2016-01-20 10:53:25,220 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: stopIdle()
2016-01-20 10:53:25,220 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: stopProgressBar
2016-01-20 10:53:25,220 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: idleThread.quit()
2016-01-20 10:53:25,220 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: _idleThread.wait()
2016-01-20 10:53:25,220 (steam_idle_qt.QIdle.Idle.doStopIdle) [DEBUG] doStopIdle called
2016-01-20 10:53:25,220 (steam_idle_qt.QIdle.Idle._stopIdle) [DEBUG] _stopIdle called
2016-01-20 10:53:25,220 (steam_idle_qt.QIdle.Idle.doStopIdle) [DEBUG] sending finished signal
2016-01-20 10:53:25,220 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: _multiIdleThread.quit()
2016-01-20 10:53:25,221 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: _multiIdleThread.wait()
2016-01-20 10:53:25,221 (steam_idle_qt.ui.mainwindow.MainWindow.cleanUp) [DEBUG] cleanUp: DONE
2016-01-20 10:53:25,222 (steam_idle_qt.ui.mainwindow.MainWindow._post_stopIdle) [DEBUG] activeApps: "[None]"
Traceback (most recent call last):
  File "/home/code/steam_idle/steam_idle_qt/ui/mainwindow.py", line 322, in _post_stopIdle
    ).setIcon(QIcon())
AttributeError: 'NoneType' object has no attribute 'appid'
QThread: Destroyed while thread is still running
```

**Comment by jayme-github** [comment]
move to https://github.com/jayme-github/steam_idle_qt/issues/1
